web/router.ex
defmodule App.Router do
  use App.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug App.Locale
  end

  scope "/", App do
    pipe_through :browser

    get "/", PageController, :index

    get  "/signup", SignupController, :index
    post "/signup", SignupController, :create

    get  "/login", LoginController, :index
    get  "/login/:login", LoginController, :show
    post "/login", LoginController, :create

    get "/logout", LogoutController, :index

    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      resources "/tweets", TweetController, only: [:create]

      get "/followers", FollowerController, :index
      get "/following", FollowingController, :index
      get "/favorites", FavoriteController, :index

      post   "/follow", FollowerController, :create
      delete "/follow", FollowerController, :delete
    end

    resources "/tweets", TweetController, only: [:index, :delete] do
      post   "/favorite", FavoriteController, :create
      delete "/favorite", FavoriteController, :delete

      post   "/retweet", RetweetController, :create
      delete "/retweet", RetweetController, :delete
    end

    get "/hashtag/:name", TagController, :show

    get "/locale/:locale", LocaleController, :new
  end
end

web/models/user.ex
defmodule App.User do
  use App.Web, :model

  import Plug.Conn

  schema "users" do
    field :login, :string
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    field :new_password, :string, virtual: true
    field :new_password_confirmation, :string, virtual: true
    field :password_hash, :string
    field :name, :string
    field :email, :string
    field :profile_picture, :string
    field :follower_id, :integer, virtual: true
    has_many :tweets, App.Tweet
    has_many :followers, App.Follower, foreign_key: :user_id
    has_many :following, App.Follower, foreign_key: :follower_id
    has_many :favorites, App.Favorite, foreign_key: :user_id
    has_many :retweets, App.Retweet, foreign_key: :user_id

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:login, :password, :password_hash, :new_password, :name, :email, :profile_picture])
    |> validate_required([:login, :password, :name])
    |> validate_length(:login, max: 15)
    |> validate_length(:name, max: 20)
    |> validate_confirmation(:password)
    |> validate_confirmation(:new_password)
    |> unique_constraint(:login)
  end

  @doc """
  Populates changeset with password hash from password.

  It will automatically generate a salt before hashing the password.
  """
  def with_password_hash(changeset) do
    password = Ecto.Changeset.get_change(changeset, :password)
    hash = Comeonin.Bcrypt.hashpwsalt(password)
    Ecto.Changeset.put_change(changeset, :password_hash, hash)
  end

  @doc """
  Validate password against hash.
  """
  def validate_password(password, hash) do
    Comeonin.Bcrypt.checkpw(password, hash)
  end

  @doc """
  Get current user from connection or session (if present), nil otherwise.
  """
  def get_current_user(conn) do
    case conn.assigns[:current_user] do
      nil ->
        Plug.Conn.get_session(conn, :current_user)
      current_user ->
        current_user
    end
  end

  @doc """
  Put user as current user to connection and session. The new connection is
  returned.
  """
  def put_current_user(conn, user) do
    current_user = %{id: user.id, login: user.login, name: user.name}
    conn
    |> assign(:current_user, current_user)
    |> put_session(:current_user, current_user)
  end
end

web/controllers/user_controller.ex
defmodule App.UserController do
  use App.Web, :controller

  alias App.Tweet
  alias App.User

  import Ecto.Changeset

  plug App.LoginRequired when action in [:edit, :update]
  plug App.SetUser when action in [:show]

  def index(conn, _params) do
    users = Repo.all User |> order_by([u], [asc: u.name])
    render conn, "index.html", users: users
  end

  def show(conn, _params) do
    user = conn.assigns[:user]
    changeset = Tweet.changeset %Tweet{}
    render conn, "show.html", user: user, changeset: changeset
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get! User, id
    changeset = User.changeset user
    render conn, "edit.html", user: user, changeset: changeset
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get! User, id
    changeset = User.changeset user, user_params

    # authorize user update
    password = get_change(changeset, :password)
    unless User.validate_password password, user.password_hash do
      new_changeset = %{changeset | action: :update } |> add_error(:password, gettext "wrong password")
      render conn, "edit.html", user: user, changeset: new_changeset
    end

    # set new password? (optional)
    new_password = get_change changeset, :new_password
    changeset = if String.length(new_password) > 0 do
      put_change(changeset, :password, new_password) |> User.with_password_hash
    else
      changeset
    end

    photo = user_params["photo"]
    changeset = if photo do
      name = "profile_picture_" <> id
      dst = Path.join([:code.priv_dir(:app), "static", "images", name])
      File.cp! photo.path, dst
      put_change changeset, :profile_picture, name
    else
      changeset
    end

    case Repo.update changeset do
      {:ok, user} ->
        conn
        |> put_flash(:info, gettext "Settings updated successfully")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render conn, "edit.html", user: user, changeset: changeset
    end
  end
end

web/views/user_view.ex
defmodule App.UserView do
  use App.Web, :view
end

web/templates/user/edit.html.eex
<div class="row">
  <div class="col-lg-12">
    <div class="area">
      <h4><%= gettext "Settings" %></h4>
    </div>
    <div class="area">
      <%= render "form.html", changeset: @changeset, action: user_path(@conn, :update, @user) %>
    </div>
  </div>
</div>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <div class="form-group">
    <label class="control-label"><%= gettext "Name" %></label>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <label class="control-label"><%= gettext "Email (Optional)" %></label>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <label class="control-label"><%= gettext "Profile picture" %></label>
    <%= file_input f, :photo, class: "form-control" %>
    <%= error_tag f, :profile_picture %>
  </div>

  <div class="form-group">
    <label class="control-label"><%= gettext "Current password" %></label>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <label class="control-label"><%= gettext "New password" %></label>
    <%= password_input f, :new_password, class: "form-control" %>
    <%= error_tag f, :new_password %>
  </div>

  <div class="form-group">
    <label class="control-label"><%= gettext "New password confirmation" %></label>
    <%= password_input f, :new_password_confirmation, class: "form-control" %>
    <%= error_tag f, :new_password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit gettext("Update"), class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<div class="row">
  <div class="col-lg-12">
    <div class="area"><h4><%= gettext "Users" %></h4></div>
    <%= for user <- @users do %>
      <%= render App.SharedView, "user_item.html", conn: @conn, user: user %>
    <% end %>
  </div>
</div>

web/templates/user/show.html.eex
<div class="row">
  <div class="col-lg-4">
    <%= render App.SharedView, "user_info.html", conn: @conn, user: @user, active: "tweets" %>
  </div>

  <div class="col-lg-8">
    <div class="area"><h4><%= gettext "Tweets" %></h4></div>
    <%= if user_profile(@conn) do %>
      <div class="area">
        <%= render App.TweetView, "form.html", changeset: @changeset, action: user_tweet_path(@conn, :create, @user.id) %>
      </div>
    <% end %>
    <%= for tweet <- @user.tweets do %>
      <%= render App.SharedView, "tweet_item.html", conn: @conn, user: @user, tweet: tweet %>
    <% end %>
  </div>
</div>