web/router.ex
defmodule App.Router do
  use App.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug App.Locale
  end

  scope "/", App do
    pipe_through :browser

    get "/", PageController, :index

    get  "/signup", SignupController, :index
    post "/signup", SignupController, :create

    get  "/login", LoginController, :index
    get  "/login/:login", LoginController, :show
    post "/login", LoginController, :create

    get "/logout", LogoutController, :index

    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      resources "/tweets", TweetController, only: [:create]

      get "/followers", FollowerController, :index
      get "/following", FollowingController, :index
      get "/favorites", FavoriteController, :index

      post   "/follow", FollowerController, :create
      delete "/follow", FollowerController, :delete
    end

    resources "/tweets", TweetController, only: [:index, :delete] do
      post   "/favorite", FavoriteController, :create
      delete "/favorite", FavoriteController, :delete

      post   "/retweet", RetweetController, :create
      delete "/retweet", RetweetController, :delete
    end

    get "/hashtag/:name", TagController, :show

    get "/locale/:locale", LocaleController, :new
  end
end

web/views/layout_view.ex
defmodule App.LayoutView do
  use App.Web, :view

  import Plug.Conn

  def current_locale(conn) do
    conn.params["locale"] || get_session(conn, :locale)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tweeter</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= page_path(@conn, :index) %>">Tweeter</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= user_path(@conn, :index) %>"><%= gettext "Users" %></a></li>
            <li><a href="<%= tweet_path(@conn, :index) %>"><%= gettext "Tweets" %></a></li>
            <%= if current_user(@conn) do %>
              <li><a href="<%= user_path(@conn, :show, current_user(@conn).id) %>"><%= gettext "Profile" %></a></li>
              <li><a href="<%= logout_path(@conn, :index) %>"><%= gettext "Logout" %></a></li>
            <% else %>
              <li><a href="<%= signup_path(@conn, :index) %>"><%= gettext "Signup" %></a></li>
              <li><a href="<%= login_path(@conn, :index) %>"><%= gettext "Login" %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= if assigns[:changeset] && @changeset.action do %>
        <div class="alert alert-danger">
          <p><%= gettext "Oops, something went wrong! Please check the errors below." %></p>
        </div>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>
      window.onload = function() {
        require("web/static/js/app").App.run();
      }
    </script>
  </body>
</html>