web/router.ex
defmodule App.Router do
  use App.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug App.Locale
  end

  scope "/", App do
    pipe_through :browser

    get "/", PageController, :index

    get  "/signup", SignupController, :index
    post "/signup", SignupController, :create

    get  "/login", LoginController, :index
    get  "/login/:login", LoginController, :show
    post "/login", LoginController, :create

    get "/logout", LogoutController, :index

    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      resources "/tweets", TweetController, only: [:create]

      get "/followers", FollowerController, :index
      get "/following", FollowingController, :index
      get "/favorites", FavoriteController, :index

      post   "/follow", FollowerController, :create
      delete "/follow", FollowerController, :delete
    end

    resources "/tweets", TweetController, only: [:index, :delete] do
      post   "/favorite", FavoriteController, :create
      delete "/favorite", FavoriteController, :delete

      post   "/retweet", RetweetController, :create
      delete "/retweet", RetweetController, :delete
    end

    get "/hashtag/:name", TagController, :show

    get "/locale/:locale", LocaleController, :new
  end
end

web/views/shared_view.ex
defmodule App.SharedView do
  use App.Web, :view

  @months %{1 => gettext("Jan"), 2 => gettext("Feb"), 3 => gettext("Mar"),  4 => gettext("Apr"),  5 => gettext("May"),  6 => gettext("Jun"),
            7 => gettext("Jul"), 8 => gettext("Aug"), 9 => gettext("Sep"), 10 => gettext("Oct"), 11 => gettext("Nov"), 12 => gettext("Dec")}

  def format_datetime({{y, m, d}, _}) do
    String.Chars.to_string(:io_lib.format("~s ~p, ~p", [@months[m], d, y]))
  end

  def format_datetime(datetime) do
    {:ok, dump} = Ecto.DateTime.dump(datetime)
    format_datetime(dump)
  end

  def authenticated(conn) do
    current_user(conn) != nil
  end
end

web/templates/shared/tweet_item.html.eex
<div class="area">
  <div class="media">
    <div class="media-left">
      <img class="profile-picture" src="<%= static_path(@conn, "/images/" <> @tweet.user.profile_picture) %>" width="45" height="45">
    </div>
    <div class="media-body">
      <%= if assigns[:user] && @tweet.retweet_id do %>
        <div class="small-text">
          <i class="fa fa-retweet fa-retweeted"></i> <%= @user.name %> <%= gettext "retweeted" %>
        </div>
      <% end %>

      <div class="meta">
        <span class="name"><a href="<%= user_path(@conn, :show, @tweet.user.id) %>"><%= @tweet.user.name %></a></span>
        <span class="small-text">@<%= @tweet.user.login %></span>
        <span class="small-text"><%= format_datetime(@tweet.inserted_at) %></span>
      </div>

      <div class="text">
        <%= @tweet.text %>
      </div>

      <div class="action">
        <%= if @tweet.current_user_retweet_id do %>
          <%= link(raw("<i class=\"fa fa-twitter\"></i>"), to: tweet_retweet_path(@conn, :delete, @tweet.id), class: "retweeted", method: "delete") %>
        <% else %>
          <%= link(raw("<i class=\"fa fa-twitter\"></i>"), to: tweet_retweet_path(@conn, :create, @tweet.id), class: "retweet", method: "create") %>
        <% end %>

        <%= if @tweet.current_user_favorite_id do %>
          <%= link(raw("<i class=\"fa fa-heart\"></i>"), to: tweet_favorite_path(@conn, :delete, @tweet.id), class: "favorited", method: "delete") %>
        <% else %>
          <%= link(raw("<i class=\"fa fa-heart\"></i>"), to: tweet_favorite_path(@conn, :create, @tweet.id), class: "favorite", method: "create") %>
        <% end %>

        <%= if user_profile(@conn) && @tweet.retweet_id === nil do %>
          <%= link(raw("<i class=\"fa fa-trash\"></i>"), to: tweet_path(@conn, :delete, @tweet.id), class: "pull-right", method: "delete") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

web/templates/shared/user_follow.html.eex
<%= if authenticated(@conn) && !user_profile(@conn) do %>
  <%= if @user.follower_id do %>
    <%= link(gettext("Unfollow"), class: "user-follow", to: user_follower_path(@conn, :delete, @user.id), method: "delete") %>
  <% else %>
    <%= link(gettext("Follow"), class: "user-follow", to: user_follower_path(@conn, :create, @user.id), method: "post") %>
  <% end %>
<% end %>

web/templates/shared/user_info.html.eex
<div class="area">
  <div class="clearfix">
    <img class="profile-picture" src="<%= static_path(@conn, "/images/" <> @user.profile_picture) %>" width="100" height="100">
    <h4><%= @user.name %></h4>
    <%= render App.SharedView, "user_follow.html", conn: @conn, user: @user %>
  </div>
</div>

<%= render App.SharedView, "user_stats.html", conn: @conn, user: @user, active: @active %>

web/templates/shared/user_item.html.eex
<div class="area">
  <div class="meta">
    <img class="profile-picture" src="<%= static_path(@conn, "/images/" <> @user.profile_picture) %>" width="23" height="23">
    <span class="name"><a href="<%= user_path(@conn, :show, @user.id) %>"><%= @user.name %></a></span>
    <span class="small-text">@<%= @user.login %></span>
  </div>
</div>

web/templates/shared/user_stats.html.eex
<div class="area">
  <div class="user-stats">
    <div class="stats">
      <div class="header"><%= gettext "Tweets" %></div>
      <div class="content <%= if @active === "tweets" do %>active<% end %>"><a href="<%= user_path(@conn, :show, @user.id) %>"><%= length(@user.tweets) %></a></div>
    </div>
    <div class="stats">
      <div class="header"><%= gettext "Following" %></div>
      <div class="content <%= if @active === "following" do %>active<% end %>"><a href="<%= user_following_path(@conn, :index, @user.id) %>"><%= length(@user.following) %></a></div>
    </div>
    <div class="stats">
      <div class="header"><%= gettext "Followers" %></div>
      <div class="content <%= if @active === "followers" do %>active<% end %>"><a href="<%= user_follower_path(@conn, :index, @user.id) %>"><%= length(@user.followers) %></a></div>
    </div>
    <div class="stats">
      <div class="header"><%= gettext "Favorites" %></div>
      <div class="content <%= if @active == "favorites" do %>active<% end %>"><a href="<%= user_favorite_path(@conn, :index, @user.id) %>"><%= length(@user.favorites) %></a></div>
    </div>
  </div>
</div>